workflows:
  build-android-debug:
    name: Debug Android Build Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: npm install

      - name: Clean project
        script: npm run clean || true

      - name: Prepare NativeScript platform for Android
        script: npx tns prepare android

      - name: Build Debug APK
        script: npx tns build android --no-watch

      - name: Archive Debug APK
        script: |
          mkdir -p $CM_BUILD_DIR/apk
          cp platforms/android/app/build/outputs/apk/debug/app-debug.apk $CM_BUILD_DIR/apk/
    artifacts:
      - $CM_BUILD_DIR/apk/app-debug.apk
